# Generated by Django 4.2 on 2023-04-08 11:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_initial'),
        ('groups', '0002_initial'),
        ('channel', '0002_initial'),
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='channels',
            field=models.ManyToManyField(related_name='channels', through='channel.Member', to='channel.channel'),
        ),
        migrations.AddField(
            model_name='user',
            name='chat_groups',
            field=models.ManyToManyField(related_name='groups', through='groups.Member', to='groups.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='chats',
            field=models.ManyToManyField(through='chats.Chat', to=settings.AUTH_USER_MODEL),
        ),
    ]
