# Generated by Django 4.2 on 2023-04-08 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=64)),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('private', models.BooleanField(default=False, help_text='Private')),
                ('notifications', models.BooleanField(default=True, help_text='Push notifications')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.BooleanField(default=False, help_text='Designates if the member is an admin')),
                ('banned', models.BooleanField(default=False, help_text='Designates if the member is banned')),
                ('notifications', models.BooleanField(default=True, help_text='Push notifications')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='Message', null=True)),
                ('photo', models.ImageField(blank=True, help_text='Photo', null=True, upload_to='')),
                ('file', models.FileField(blank=True, help_text='File', null=True, upload_to='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('replies', models.ManyToManyField(to='groups.message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
