# Generated by Django 4.2.4 on 2023-08-15 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Name', max_length=64)),
                ('description', models.TextField(blank=True, help_text='Description', null=True)),
                ('private', models.BooleanField(default=False, help_text='Private')),
                ('notifications', models.BooleanField(default=True, help_text='Push notifications')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
